title: Project Image
accept: image/jpeg, image/png

columns:
  main:
    width: 1/2
    sections:
      content:
        type: fields
        fields:
          caption:
            label: Caption
            type: textarea
            size: small
  sidebar:
    width: 1/2
    sections:
      meta:
        type: fields
        fields:
          panorama:
            label: Panorama Photo
            type: toggle
          alt:
            label: Alternative Text
            type: text
          photographer:
            label: Photogapher
            type: text
